### ISSUE TITLE
MGMT sockets doesn't close ever?

### ISSUE THREAD

**Issue by Magalex2x14** [ukBaz/python-btsocket#1]
Hello!
I noticed that each time `btmgmt_sync.send()` is called, the newly created sockets are not closed until the program terminates:
btmon output:
```
@ MGMT Open: hass (privileged) version 1.18                       {0x0004} 0.556295
@ MGMT Open: hass (privileged) version 1.18                       {0x0003} 0.556296
@ MGMT Open: hass (privileged) version 1.18                       {0x0002} 0.556297
@ MGMT Open: hass (privileged) version 1.18                       {0x0001} 0.556297
```
However, in the btmgmt_sync.send() code, I see calls to the close method.
I wonder why this happens, what is fraught with, and how to solve it?

**Comment by ukBaz** [comment]
I've spent some time looking at this using the [examples/sync_list_commands.py](https://github.com/ukBaz/python-btsocket/blob/close_socket/examples/sync_list_commands.py) as my test case.

The problem seems to be that the underlying socket created with `libc` isn't getting removed or closed.

In my test I've observed that the libc file descriptor (fd) is always one less that the python file descriptor. so my experiment was to find the fd by subtracting one from the python fd.
https://github.com/ukBaz/python-btsocket/blob/b7a0c79de57179c1f22e4fdaa98c188dacb6aea9/btsocket/btmgmt_socket.py#L74-L80
to get the fd to close both.

Closing both fd's seems to solve the problem. However I don't think assuming the two fd's will be consecutive numbers is a good assumption to go to release with. 

I'll have a think about it and come back to it. If you have any ideas or suggestions then please let me know.

**Comment by Magalex2x14** [comment]
Thanks for pointing the way! I let you know if I find anything useful.

**Comment by ukBaz** [comment]
It appears that using `socket.close(fd)` is preferred to `os.close(fd)`

**Comment by Magalex2x14** [comment]
I found [this](https://docs.python.org/3/library/socket.html#socket.socket):
```
class socket.socket(family=AF_INET, type=SOCK_STREAM, proto=0, fileno=None)
```
...
If fileno is specified, the values for family, type, and proto are auto-detected from the specified file descriptor. Auto-detection can be overruled by calling the function with explicit family, type, or proto arguments. This only affects how Python represents e.g. the return value of [socket.getpeername()](https://docs.python.org/3/library/socket.html#socket.socket.getpeername) but not the actual OS resource. 

**Unlike** [socket.fromfd()](https://docs.python.org/3/library/socket.html#socket.fromfd), **fileno will return the same socket and not a duplicate. This may help close a detached socket using** [socket.close()](https://docs.python.org/3/library/socket.html#socket.close).


So i tried the following and it works:
```python
#.........
def sclose(socket_fd):
    fd = socket_fd.detach()
    print('Python fd', fd)
    socket_fd.close()
    socket.close(fd)
    print(socket_fd._closed)
#.........
sock_fd = socket.socket(AF_BLUETOOTH, SOCK_RAW, BTPROTO_HCI, fileno=fd)
#.........
while True:
    pass
```

Output:
```
Python fd 3
True
Raw response: Response(header=<event_code=CommandCompleteEvent....
..........

@ MGMT Open: python3 (privileged) version 1.18             {0x000b} 2030.212335
@ MGMT Command: Read Management Support.. (0x0002) plen 0  {0x000b} 2030.212381
@ MGMT Event: Command Complete (0x0001) plen 245           {0x000b} 2030.212386
@ MGMT Close: python3                                      {0x000b} 2030.212789
```

**Comment by ukBaz** [comment]
Excellent find!

I have done the following commit with your suggested change: 9c7ec3330464fd8de0d3efa38d912b83a156d608
(And removed the sleep from the example I was using for testing b5d3bdd9e66bd64e00ca1b2235a3115716b95f34)

From my simple testing it seems to work. Did you want to do some more testing? If it is OK I can merge it with the main branch and update PyPI

**Comment by Magalex2x14** [comment]
it also works like this:
```python
sock_fd = socket.socket(AF_BLUETOOTH, fileno=fd)
```
because of "...If fileno is specified, the values for family, type, and proto are auto-detected from the specified file descriptor. Auto-detection can be overruled by calling the function with explicit family, type, or proto arguments."

**Comment by Magalex2x14** [comment]
I want to try it on another platform little bit later. I will let you know.

**Comment by Magalex2x14** [comment]
Yes, it works. I don't see anything suspicious 🤷‍♂️

**Comment by ukBaz** [comment]
Fix uploaded to https://pypi.org/project/btsocket/ 

Any issues then please open a new ticket.

Thanks for your collaboration @Magalex2x14  on resolving this issue. Very much appreciated.
