### ISSUE TITLE
btmgmt_sync.send('ReadControllerIndexList') fails to compose the packet for request...

### ISSUE THREAD

**Issue by antoniovazquezblanco** [ukBaz/python-btsocket#8]
The `ReadControllerIndexList` seems to be the only one that does not require an idx to be sent. At the same time, when trying to call it, the command fails with a `AttributeError: 'NoneType' object has no attribute 'encode'`

**Comment by ukBaz** [comment]
I think the `ReadControllerIndexList` command is one of a few where the Controller Index can have a special value of `<non-controller>` to indicate that command or event is not related to any specific controller.

According to the BlueZ API docs a value of `0xFFFF` represents  `<non-controller>`

I did the following quick test and it seemed to get a response for me:

```python
>>> from btsocket import btmgmt_sync
>>> data = btmgmt_sync.send('ReadControllerIndexList', None)
>>> data
Response(header=<event_code=CommandCompleteEvent, controller_idx=65535, param_len=7>, event_frame=<command_opcode=ReadControllerIndexList, status=Success>, cmd_response_frame=<num_controllers=1, controller_index[i]=[0]>)
```

Do you have an example of how to reproduce this?

**Comment by antoniovazquezblanco** [comment]
Oh, now I see. Your example works as intended!
It may be interesting to show this as an example in the readme for documentation maybe.

One last question, how do you access the controller_index array?
```python
>>> print(response.cmd_response_frame.controller_index[i])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Packet' object has no attribute 'controller_index'. Did you mean: 'controller_index[i]'?
>>> print(response.cmd_response_frame.'controller_index[i]')
  File "<stdin>", line 1
    print(response.cmd_response_frame.'controller_index[i]')
                                      ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax
>>> print(response.cmd_response_frame['controller_index[i]'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Packet' object is not subscriptable
```

Thanks!

**Comment by ukBaz** [comment]
>  It may be interesting to show this as an example in the readme for documentation maybe.

Yes, something in the README about `<non-controller>` is probably a good idea. 

> One last question, how do you access the controller_index array?

To use my example above:
```python
>>> data.cmd_response_frame.__getattribute__('controller_index[i]')
[0]
```

Which is clearly not practical (or intended). This looks to be introduced because of the automatic generation of the structure from the API documentation which has the parameter name `Controller_Index[i]` 

There are a few others with a similar looking issue and need the `[i]` removed  :-(

**Comment by antoniovazquezblanco** [comment]
Thanks for the solutions! I am happy to be able to use the lib. I will close the issue as solved for me. :)
